apiVersion: batch/v1
kind: CronJob
metadata:
  name: print-time-cronjob
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: print-time
            image: busybox
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - echo "Time now is "; date +\%T
          restartPolicy: OnFailure